services:
  postgres:
    image: postgres:16
    container_name: svc-auth-postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: svc-auth

    ports:
      - "8007:5432"

    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
